title: Young Woo Song
logo: /headshot/Headshot.png
description: Aspiring Data Scientist bringing a unique blend of creativity, precision, and problem-solving skills.
# show_downloads: false
theme: jekyll-theme-minimal
